name: Qscanner Integration with GitHub Actions

on:
  workflow_dispatch: # This allows you to trigger the workflow manually

jobs:
  docker-scan:
    runs-on: ubuntu-latest

    steps:
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Pull the Docker image from Docker Hub
      - name: Pull Docker Image
        run: docker pull nuxeo:latest

      # Install Qscanner for scanning the image
      - name: Install Qscanner
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://www.qualys.com/qscanner/download/v4.1.0/download_qscanner.sh
          chmod +x download_qscanner.sh
          ./download_qscanner.sh

      # Scan the Docker image with Qscanner for vulnerabilities
      - name: Scan Docker Image with Qualys Qscanner
        run: |
          ./linux-amd64/qscanner image nuxeo:latest --pod US2 --access-token "${{ secrets.QUALYS_ACCESS_TOKEN }}"
        continue-on-error: true

      # Fail the workflow if high or critical vulnerabilities are found
      - name: Check scan result
        if: failure()
        run: exit 1

      # Push the image to Docker Hub if the scan passed
      - name: Push Docker Image to Docker Hub
        if: success()
        run: docker push your-docker-image:your-docker-tag
